title: Starterkit

options:
  changeTitle: false
  changeStatus: false
  changeTemplate: false
  changeSlug: false
  delete: false

tabs:
  pages:
    icon: layers
    sections:
      pages:
        headline: Pages
        type: pages
        status: all
        sortable: false
